### ISSUE TITLE
Could you please share me the requirement document of this repo?

### ISSUE THREAD

**Issue by evzlk** [tjenki35/ssl-file-server#1]
I read all your codes in this repo and think it's really fantastic!
Could you please share the requirement docs or writeup of this homework?( a web link is nice)
Now I want to implement a SSL server by using C++, so I think your work will help me.
Thanks a lot!

**Comment by tjenki35** [comment]
Unfortunately we are not allowed to post any assignment specs from our University.

**Comment by tjenki35** [comment]
Here is the book we used for the class however https://books.google.com/books?id=wxMqaz4JMb0C&printsec=frontcover&dq=network+security+books&hl=en&sa=X&ved=0ahUKEwiPwamykOzZAhUKxWMKHcxdBi4Q6AEIJDAA

**Comment by evzlk** [comment]
Great! The book will be helpful to me.
Could you offer me the course name or No.? I think that I can search for it by my own.
Thank you anyway.
